[params]
# Smart Link Options
[params.smartLinkOptions]
output = "markdown"

# Smart Wiki Links - Basic configuration
[[params.smartWikiLinks]]
name = "WikiLink"
wikiLink = true
stripNamespace = true 
class = "wikilink" # Only used when output: html

[[params.smartWikiLinks]]
name = "Broken Link"
pattern = "^.*$"
url = "/broken-link/"
class = "broken-link" # Only used when output: html