[params]
# SmartLink Module Configuration
[params.modules]
  [params.modules.smartlink]
    # Output format for SmartLinks
    output = "html"
    disable = false
    # Supported file extensions for SmartLink processing
    supportExts = ["md"]
    # Use page title as label when no custom label is provided
    usePageTitle = false
    # Use page title as label for links with these prefixes
    usePageTitlePrefixes = []
    # Normalize escaped wikilinks (e.g., \[\[link\]\] -> [[link]])
    normalizeEscapedWikilink = true
    protectCodeBlocks = false
    maxCodeBlockIterations = 50
    stripNamespacePrefixes = []
    # URL prefix aliases for mapping
    [params.modules.smartlink.prefixAlias]
      # Example: "github:" -> "https://github.com/"
      # "docs:" -> "/docs/"
    
    # SmartLink rules configuration
    [[params.modules.smartlink.rules]]
      name = "WikiLink"
      wikiLink = true
      stripNamespace = true
      class = "wikilink"
    
    [[params.modules.smartlink.rules]]
      name = "Broken Link"
      pattern = "^.*$"
      url = "/broken-link/?path={0}"
      class = "broken-link"